version: "1"
services:
  app:
    image: go-hello-world:v1
  redis:
    image: redis:5.0.12
    command: redis-server --requirepass redispass
    ports:
      - 6379:6379
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=praisindo
    ports:
      - 5432:5432
