services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    hostname: es01
    container_name: es01
    ports:
      - "9200:9200"
    environment:
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
      xpack.security.http.ssl.enabled: false
      xpack.license.self_generated.type: trial
    networks:
      - elastic-net
  kib01:
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: kibana_system
      xpack.security.enabled: false
      xpack.license.self_generated.type: trial
    networks:
      - elastic-net
networks:
  elastic-net: